apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-ubuntu-ssh-1
  name: my-ubuntu-ssh-1
spec:
  containers:
  - image: vjkancherla/my-ubuntu-ssh:v1
    name: my-ubuntu-ssh
    ports:
    - containerPort: 22
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-ubuntu-ssh-2
  name: my-ubuntu-ssh-2
spec:
  containers:
  - image: vjkancherla/my-ubuntu-ssh:v1
    name: my-ubuntu-ssh
    ports:
    - containerPort: 22
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-ubuntu-ssh-1
  name: ubuntu-svc-1
spec:
  ports:
  - port: 2222
    protocol: TCP
    targetPort: 22
  selector:
    run: my-ubuntu-ssh-1
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-ubuntu-ssh-2
  name: ubuntu-svc-2
spec:
  ports:
  - port: 2322
    protocol: TCP
    targetPort: 22
  selector:
    run: my-ubuntu-ssh-2
status:
  loadBalancer: {}