---
- name: Ensure Nginx package is installed
  apt:
    name: nginx
    state: present
  register: nginx_pkg

- name: Check if Port 80 is already in use
  wait_for:
    host: 127.0.0.1
    port: 80
    state: stopped
    timeout: 2
  ignore_errors: yes
  register: port_80_status
  when: nginx_pkg.changed

# - name: Print the content of the registered variable
#   debug:
#     var: nginx_pkg


- block:
    - name: Set nginx_port to 8080 if condition is met
      set_fact:
        nginx_port: "{{ nginx_alt_listen_port }}"

    - name: Create a backup of the original Nginx configuration
      command: cp /etc/nginx/sites-available/default /tmp/default.bak
      ignore_errors: yes
      register: backup_result

    - name: Replace "listen 80 default_server;" with "listen 8080 default_server;"
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen 80 default_server;'
        line: 'listen {{ nginx_port }} default_server;'

    - name: Replace "listen [::]:80 default_server;" with "listen [::]:8080 default_server;"
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen \[::\]:80 default_server;'
        line: 'listen [::]:{{ nginx_port }} default_server;'

  when: port_80_status.failed

- name: Ensure Nginx service is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Configure Nginx virtual host
  template:
    src: templates/nginx_vhost.conf.j2
    dest: /etc/nginx/sites-available/mywebsite
  notify: reload Nginx

- name: Enable the Nginx virtual host
  command: ln -s /etc/nginx/sites-available/mywebsite /etc/nginx/sites-enabled/
  args:
    creates: /etc/nginx/sites-enabled/mywebsite
  notify: reload Nginx

- name: Disable the default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload Nginx
