---
- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present

- name: Install npm modules required by our app
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ node_npm_modules }}"