---
- hosts: db
  become: yes

  roles:
    - role: vjk.mysql
      vars:
        mysql_name: "{{ _mysql_name }}"
        mysql_service: "{{ _mysql_service }}"
        mysql_databases: "{{ _mysql_databases }}"
        mysql_users: "{{ _mysql_users }}"


- hosts: app-server-1.127.0.0.1.nip.io
  become: yes

  roles:
    - role: vjk.nginx
      vars:
        nginx_vhosts: "{{ nginx_custom_vhosts }}"

    # - role: vjk.php
    #   vars:

  
  tasks:
    - name: Run common tasks
      include_tasks: tasks/common.yaml

    - name: Run post-install nginx tasks
      include_tasks: tasks/post-install-nginx.yaml
      
            