---
# - hosts: db
#   become: yes

#   roles:
#     - role: vjk.mysql
#       vars:
#         mysql_name: mysql
#         mysql_service: mysql
#         mysql_databases:
#           - name: wordpress
#             state: present
#             encoding: utf8
#             collation: utf8_bin
#         mysql_users:
#           - name: wordpress_user
#             state: present
#             password: Secret123!
#             priv: "wordpress.*:ALL"
#             update_password: on_create


- hosts: app-server-1.127.0.0.1.nip.io
  become: yes

  roles:
    - role: vjk.nginx
      vars:
        nginx_vhosts:
          - listen: "80"
            server_name:  "{{ ansible_hostname }}"
            root: "/var/www/{{ ansible_hostname }}"
            index: "index.html index.htm"
            filename: "{{ ansible_hostname }}.conf"
  tasks:
    - name: Test nginx response
      uri:
        url: http://{{ ansible_hostname }}:80/
        status_code: 200
      register: response
      until: response.status == 200
      retries: 5
      delay: 2
            