---
- hosts: app-server-1.127.0.0.1.nip.io
  become: yes

  roles:
    - role: buluma.mysql
      vars:
        mysql_name: mysql
        mysql_service: mysql

    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql