---
    roles:
        # From Ansible Galaxy, latest version.
        # - name: geerlingguy.mysql

        # From Ansible Galaxy, latest version.
        - name: buluma.mysql

        # From Ansible Galaxy, latest version.
        - name: geerlingguy.apache

        # From Ansible Galaxy, latest version.
        - name: geerlingguy.php

        # From Ansible Galaxy, latest version.
        - name: geerlingguy.php-mysql