---
- name: Common Pre-Task
  hosts: all # 
  become: yes  # Use sudo privileges

  pre_tasks:
    - name: Update apt cache if needed.
      apt: 
        update_cache: true 
        cache_valid_time: 3600

- name: Deploy Nginx on App servers
  hosts: app # On all hosts in [app] group
  become: yes  # Use sudo privileges

  # pre_tasks:
  #   - name: Update apt cache if needed.
  #     apt: 
  #       update_cache: true 
  #       cache_valid_time: 3600

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Copy Nginx configuration template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Ensure Nginx configuration is enabled
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


- name: Install Solr on DB server
  hosts: db
  become: yes  # Use sudo privileges

  # pre_tasks:
  #   - name: Update apt cache if needed.
  #     apt: 
  #       update_cache: true 
  #       cache_valid_time: 3600
  
  tasks:
    - name: Install Java.
      apt: 
        name: openjdk-11-jdk 
        state: present

    - name: Download Solr. 
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz" 
        checksum: "{{ solr_checksum }}"

    - name: Expand Solr. 
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run Solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz 
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
      notify: restart solr
   
    - name: Ensure solr is started and enabled on boot
      service: 
        name: solr 
        state: started 
        enabled: yes

  handlers:
    - name: restart solr
      service: 
        name: solr 
        state: restarted
  