apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-server-1
  name: app-server-1
spec:
  containers:
  - image: vjkancherla/my-ubuntu-ssh:v1
    name: my-ubuntu-ssh
    ports:
    - containerPort: 22
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-server-2
  name: app-server-2
spec:
  containers:
  - image: vjkancherla/my-ubuntu-ssh:v1
    name: my-ubuntu-ssh
    ports:
    - containerPort: 22
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-server-1
  name: db-server-1
spec:
  containers:
  - image: vjkancherla/my-ubuntu-ssh:v1
    name: my-ubuntu-ssh
    ports:
    - containerPort: 22
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app-server-1
  name: app-svc-1
spec:
  ports:
  - port: 2222
    protocol: TCP
    targetPort: 22
  selector:
    run: app-server-1
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app-server-2
  name: app-svc-2
spec:
  ports:
  - port: 2322
    protocol: TCP
    targetPort: 22
  selector:
    run: app-server-2
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: db-server-1
  name: db-svc-1
spec:
  ports:
  - port: 2422
    protocol: TCP
    targetPort: 22
  selector:
    run: db-server-1
status:
  loadBalancer: {}